alias: Riego Área 1
description: ""
trigger:
  - platform: time_pattern
    minutes: /10
condition:
  - condition: numeric_state
    entity_id: sensor.area_1_humidity_sensor
    below: 45
action:
  - service: switch.turn_on
    data: {}
    target:
      device_id: 0abbdb31d34fccad107029e5a1703eff
  - device_id: 9252ffdfe2d07583ec37ac3c9dc8171a
    domain: mobile_app
    type: notify
    message: Se encedio el riego del Área 1
    title: "Riego Área 1 "
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      device_id: 0abbdb31d34fccad107029e5a1703eff
  - device_id: 9252ffdfe2d07583ec37ac3c9dc8171a
    domain: mobile_app
    type: notify
    message: Se apago el riego del Área 1
    title: Riego Área 1
mode: single